In [1]:
import requests
import time
import tqdm
import pandas as pd
import os
import json
from bs4 import BeautifulSoup
import pandas as pd

import re

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

## saving all the urls for flats in copenhagen

In [2]:
# Base URL using an f-string
base_url = 'https://www.boligsiden.dk/kommune/herlev/solgte/ejerlejlighed?sortAscending=false&yearSoldFrom=2015&yearSoldTo=2023&registrationTypes=normal&page={page_number}'

# Create an empty list to store all article URLs
list_of_article_urls = []

number_pages = 10

# Loop through pages from 1 to 500
for page_number in tqdm.tqdm(range(1, number_pages+1)):
    # Define the URL for the current page using the f-string
    url = base_url.format(page_number=page_number)
    
    # Connect to the page
#     response = requests.get(url)
    
    #
    try:
        response = requests.get(url)
    except Exception as e:
        print(url) #Print url
        print(e) #Print error
        with open("list_of_article_urls", "w") as l: #Save the list_htmls as a json file to retrieve at another time
            json.dump(list_of_article_urls, l)
        continue #Continue to next iteration of the loop
    #
    
    
    # Parse data with BeautifulSoup
    soup = BeautifulSoup(response.content, 'lxml')
    
    # Find all articles on the page
    articles = soup.find_all('div', class_='shadow overflow-hidden mx-4')
    
    # Append the article URLs to the list
    for article in articles:
        article_url = article.find('a')['href']
        list_of_article_urls.append(article_url)

# Now, list_of_article_urls contains all the article URLs from pages 1 to 500
print("Total number of articles:", len(list_of_article_urls))

100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:08<00:00,  1.19it/s]

Total number of articles: 184

## saving the right url code and delete duplicates

In [3]:
base_url = 'https://www.boligsiden.dk'

list_of_article_urls = [base_url + url for url in list_of_article_urls]

list_of_article_urls = list(set(list_of_article_urls))

## scrappe standard information

In [4]:
import requests
from bs4 import BeautifulSoup
import re
import tqdm

# Create empty lists for the information we want to extract for every article
adresse_list = []
kvdm_list = []

# Iterate through each article URL
for article_url in tqdm.tqdm(list_of_article_urls):
    try:
        # Fetch HTML content from the article URL
        response = requests.get(article_url)
        response.raise_for_status()  # Raise an exception for HTTP errors

        # Create a BeautifulSoup object to parse the HTML
        soup = BeautifulSoup(response.text, "html.parser")

        # Find elements with the specified classes and extract their text content
        element_1 = soup.find(class_="font-bold text-sm md:text-base")
        text_content_1 = element_1.get_text(strip=True) if element_1 else None

        element_2 = soup.find(class_="mt-1 text-xs md:text-sm text-gray-600")
        text_content_2 = element_2.get_text(strip=True) if element_2 else None

        # Combine the text content with a space between them
        combined_text = ' '.join(filter(None, [text_content_1, text_content_2]))

        # Append combined_text to adresse_list
        adresse_list.append(combined_text)

        # Regular expression pattern to find numbers before "m²"
        pattern = r'(\d+)\s*m²'  # Grouping the digits

        # Find all matches
        matches = re.findall(pattern, response.text)

        # Append only the first number from each match to kvdm_list
        if matches:
            kvdm_list.append(int(matches[0]))
        else:
            kvdm_list.append(None)

    except requests.RequestException as e:
        print(f"Error fetching content for {article_url}: {e}")

# Now, adresse_list contains the text content of the elements with classes
# "font-bold text-sm md:text-base" and "mt-1 text-xs md:text-sm text-gray-600"
# with a space between them for each article URL
# print(adresse_list)

# Now, kvdm_list contains the first number found before "m²" for each article URL
# Converted to integers where possible, and None where no match was found
# print(kvdm_list)

100%|████████████████████████████████████████████████████████████████████████████████| 184/184 [01:44<00:00,  1.76it/s]

## DataFrame

In [5]:
# df.to_csv('København_kom.csv', index=False)

In [6]:
# Regular expression pattern to capture the desired part of each address
pattern = r'^[\wæøåÆØÅ\s]+\s\d+'

# Extract the desired part of each address
extracted_addresses = []
for address in adresse_list:
    match = re.match(pattern, address)
    if match:
        extracted_addresses.append(match.group(0))
    else:
        extracted_addresses.append(None)

        
short_addresses = list(set(extracted_addresses))

# Print the length of extracted addresses and adresse_list
# print(len(extracted_addresses), len(adresse_list))
# print(extracted_addresses)

In [7]:
print(len(short_addresses), len(adresse_list))

52 184

In [8]:
# Assuming that all lists have the same length
data = {
    'URL': list_of_article_urls,
    'Adresse': adresse_list,
    'Kort adresse': extracted_addresses,
    'Kvdm': kvdm_list
}

# Create DataFrame
df = pd.DataFrame(data)
df = df[df['Kort adresse'].notna()]
# Print DataFrame
df[:6]
# df.to_csv('København_kom.csv', index=False)

,URL,Adresse,Kort adresse,Kvdm
0,https://www.boligsiden.dk/adresse/klokkedybet-...,"Klokkedybet 3, 1. c. 2730 Herlev",Klokkedybet 3,36
1,https://www.boligsiden.dk/adresse/elverhoejen-...,"Elverhøjen 1D, st. th. 2730 Herlev",Elverhøjen 1,67
2,https://www.boligsiden.dk/adresse/herlev-hoved...,"Herlev Hovedgade 97, 1. th. 2730 Herlev",Herlev Hovedgade 97,60
3,https://www.boligsiden.dk/adresse/toggangen-7-...,"Toggangen 7, 1. th. 2730 Herlev",Toggangen 7,60
4,https://www.boligsiden.dk/adresse/elverhoejen-...,"Elverhøjen 33, 1. 2730 Herlev",Elverhøjen 33,281
5,https://www.boligsiden.dk/adresse/herlev-hoved...,"Herlev Hovedgade 66, st. th. 2730 Herlev",Herlev Hovedgade 66,76

## optimere korteadresser så man ikke slår lejligheder i i samme opgang op to gange

In [9]:
data1 = {
    'Kort adresse': short_addresses
}
df1 = pd.DataFrame(data1)
# df1

In [10]:
import googlemaps
# Initialize Google Maps API client
gmaps = googlemaps.Client(key='AIzaSyAkzxBl6dpAhqaPG3WQEDPsaK3pRsJoMjw')  # Replace 'YOUR_API_KEY' with your actual API key

# Function to geocode addresses and retrieve coordinates
def geocode_address(address):
    try:
        # Geocode address
        geocode_result = gmaps.geocode(address)
        if geocode_result:
            # Extract latitude and longitude from geocode result
            location = geocode_result[0]['geometry']['location']
            return location['lat'], location['lng']
        else:
            return None, None
    except Exception as e:
        print(f"Error geocoding address '{address}': {e}")
        return None, None

# Apply geocode_address function to 'Kort adresse' column and store results in new columns 'Latitude' and 'Longitude'
geocoded_results = df1['Kort adresse'].apply(geocode_address)

# Add Latitude and Longitude to DataFrame
df1['Latitude'], df1['Longitude'] = zip(*geocoded_results)

# Save df1 as a CSV file
df1.to_csv('df1_geocoded.csv', index=False)

# Print DataFrame with new coordinates columns
df1

                  Kort adresse   Latitude  Longitude
0          Herlev Hovedgade 93  55.721518  12.444473
1          Herlev Hovedgade 66  55.720880  12.448622
2          Herlev Hovedgade 70  55.721225  12.447313
3          Herlev Hovedgade 95  55.721384  12.444445
4         Snemandsvej 34B 2730  55.728532  12.452520
5                Elverhøjen 33  55.724298  12.449165
6                Romancevej 10  55.717205  12.445669
7   Herlev Hovedgade 188B 2730  55.725532  12.426362
8                 Kantatevej 4  55.716058  12.440528
9                Rødhættevej 7  55.723862  12.443965
10          Hjortespringvej 42  55.729533  12.437259
11        Herlev Hovedgade 105  55.722115  12.443378
12         Grønsvinget 21 2730  55.736264  12.412575
13  Herlev Hovedgade 188A 2730  55.725496  12.426375
14                Vindebyvej 1  55.725161  12.430438
15       Klausdalshave 2B 2730  55.743656  12.419755
16         Herlev Hovedgade 99  55.721889  12.444059
17         Herlev Hovedgade 97  55.721811  12.444292
18       Klausdalshave 4A 2730  55.743701  12.419792
19               Klokkedybet 3  56.579258   9.019020
20         Herlev Hovedgade 64  55.720776  12.448501
21                Vindebyvej 3  55.725254  12.430440
22                 Toggangen 5  55.721833  12.443178
23   Herlev Hovedgade 74B 2730  55.721452  12.446715
24       Klausdalshave 6A 2730  55.743804  12.419765
25         Herlev Hovedgade 87  55.721285  12.445105
26       Klausdalshave 6B 2730  55.743854  12.419714
27                Vindebyvej 5  55.725345  12.430441
28         Herlev Hovedgade 85  55.721419  12.445133
29        Herlev Hovedgade 101  55.721986  12.443829
30         Herlev Hovedgade 91  55.721661  12.444501
31         Herlev Hovedgade 89  55.721160  12.445078
32                 Toggangen 3  55.721941  12.443188
33         Herlev Hovedgade 72  55.721302  12.447050
34               Elverhøjen 16  55.721927  12.449648
35       Klausdalshave 8B 2730  55.743926  12.419685
36                 Fagotvej 14  55.717965  12.439987
37  Gammel Klausdalsbrovej 485  55.742911  12.416459
38                Elverhøjen 1  55.720959  12.449206
39         Herlev Hovedgade 60  55.720592  12.448711
40              Snehvidevej 14  55.723714  12.445406
41                 Toggangen 1  55.721884  12.443257
42          Hjortespringvej 44  55.729838  12.437190
43       Klausdalshave 4B 2730  55.743736  12.419740
44                 Toggangen 7  55.721717  12.443152
45           Krumstien 18 2730  55.736216  12.412503
46       Klausdalshave 2A 2730  55.743622  12.419814
47       Klausdalshave 8A 2730  55.743883  12.419744
48   Herlev Hovedgade 74A 2730  55.721444  12.446621
49         Herlev Hovedgade 62  55.720661  12.448427
50        Snemandsvej 34A 2730  55.728646  12.452609
51        Herlev Hovedgade 103  55.722046  12.443595

In [11]:
# Merge the two DataFrames on the 'Kort adresse' column using a left join
combined_df = pd.merge(df, df1, on='Kort adresse', how='left')

# Print the combined DataFrame
combined_df

,URL,Adresse,Kort adresse,Kvdm,Latitude,Longitude
0,https://www.boligsiden.dk/adresse/klokkedybet-...,"Klokkedybet 3, 1. c. 2730 Herlev",Klokkedybet 3,36,56.579258,9.019020
1,https://www.boligsiden.dk/adresse/elverhoejen-...,"Elverhøjen 1D, st. th. 2730 Herlev",Elverhøjen 1,67,55.720959,12.449206
2,https://www.boligsiden.dk/adresse/herlev-hoved...,"Herlev Hovedgade 97, 1. th. 2730 Herlev",Herlev Hovedgade 97,60,55.721811,12.444292
3,https://www.boligsiden.dk/adresse/toggangen-7-...,"Toggangen 7, 1. th. 2730 Herlev",Toggangen 7,60,55.721717,12.443152
4,https://www.boligsiden.dk/adresse/elverhoejen-...,"Elverhøjen 33, 1. 2730 Herlev",Elverhøjen 33,281,55.724298,12.449165
...,...,...,...,...,...,...
179,https://www.boligsiden.dk/adresse/elverhoejen-...,"Elverhøjen 1C, st. tv. 2730 Herlev",Elverhøjen 1,56,55.720959,12.449206
180,https://www.boligsiden.dk/adresse/klausdalshav...,Klausdalshave 6A 2730 Herlev,Klausdalshave 6A 2730,110,55.743804,12.419765
181,https://www.boligsiden.dk/adresse/gammel-klaus...,"Gammel Klausdalsbrovej 485G, 1. 2730 Herlev",Gammel Klausdalsbrovej 485,87,55.742911,12.416459
182,https://www.boligsiden.dk/adresse/elverhoejen-...,"Elverhøjen 1E, 2. tv. 2730 Herlev",Elverhøjen 1,60,55.720959,12.449206
183,https://www.boligsiden.dk/adresse/herlev-hoved...,"Herlev Hovedgade 66, 1. th. 2730 Herlev",Herlev Hovedgade 66,76,55.720880,12.448622

In [12]:
combined_df['Kommune'] = 'Herlev'
combined_df.to_csv('Herlev_kom.csv', index=False)
combined_df

,URL,Adresse,Kort adresse,Kvdm,Latitude,Longitude,Kommune
0,https://www.boligsiden.dk/adresse/klokkedybet-...,"Klokkedybet 3, 1. c. 2730 Herlev",Klokkedybet 3,36,56.579258,9.019020,Herlev
1,https://www.boligsiden.dk/adresse/elverhoejen-...,"Elverhøjen 1D, st. th. 2730 Herlev",Elverhøjen 1,67,55.720959,12.449206,Herlev
2,https://www.boligsiden.dk/adresse/herlev-hoved...,"Herlev Hovedgade 97, 1. th. 2730 Herlev",Herlev Hovedgade 97,60,55.721811,12.444292,Herlev
3,https://www.boligsiden.dk/adresse/toggangen-7-...,"Toggangen 7, 1. th. 2730 Herlev",Toggangen 7,60,55.721717,12.443152,Herlev
4,https://www.boligsiden.dk/adresse/elverhoejen-...,"Elverhøjen 33, 1. 2730 Herlev",Elverhøjen 33,281,55.724298,12.449165,Herlev
...,...,...,...,...,...,...,...
179,https://www.boligsiden.dk/adresse/elverhoejen-...,"Elverhøjen 1C, st. tv. 2730 Herlev",Elverhøjen 1,56,55.720959,12.449206,Herlev
180,https://www.boligsiden.dk/adresse/klausdalshav...,Klausdalshave 6A 2730 Herlev,Klausdalshave 6A 2730,110,55.743804,12.419765,Herlev
181,https://www.boligsiden.dk/adresse/gammel-klaus...,"Gammel Klausdalsbrovej 485G, 1. 2730 Herlev",Gammel Klausdalsbrovej 485,87,55.742911,12.416459,Herlev
182,https://www.boligsiden.dk/adresse/elverhoejen-...,"Elverhøjen 1E, 2. tv. 2730 Herlev",Elverhøjen 1,60,55.720959,12.449206,Herlev
183,https://www.boligsiden.dk/adresse/herlev-hoved...,"Herlev Hovedgade 66, 1. th. 2730 Herlev",Herlev Hovedgade 66,76,55.720880,12.448622,Herlev

## scrappe priserne